"""
🎨 AI Infographic Generator — Professional Corporate Style
Convert any text description into a stunning professional infographic.
Powered by Claude Opus 4.7 · White · Black · Red
"""

try:
    import pip_system_certs.wrapt_requests
except ImportError:
    pass

import streamlit as st
import anthropic
import os
import io
import base64
import tempfile
import subprocess
import sys
from datetime import datetime
from PIL import Image

try:
    from dotenv import load_dotenv
    load_dotenv(dotenv_path=os.path.join(os.path.dirname(__file__), ".env"))
except ImportError:
    pass

try:
    if "ANTHROPIC_API_KEY" in st.secrets:
        os.environ["ANTHROPIC_API_KEY"] = st.secrets["ANTHROPIC_API_KEY"]
except Exception:
    pass

# ── Playwright setup ──────────────────────────────────────────────────────────
@st.cache_resource(show_spinner="Installing Chromium renderer (first time only)…")
def install_playwright():
    # Always install browser binary first (packages.txt handles system deps)
    # playwright install is a no-op if browser already exists
    subprocess.run(
        [sys.executable, "-m", "playwright", "install", "chromium"],
        capture_output=True
    )
    # Verify the browser actually launches
    try:
        from playwright.sync_api import sync_playwright
        with sync_playwright() as p:
            browser = p.chromium.launch()
            browser.close()
        return True
    except Exception as e:
        raise RuntimeError(
            f"Chromium unavailable after install. Error: {e}\n"
            "Check that packages.txt system deps were installed correctly."
        )

# ── SYSTEM PROMPT ─────────────────────────────────────────────────────────────
def build_system_prompt(inf_type: str, width: int, height: int) -> str:
    return f"""You are the world's top corporate infographic designer with 20 years at McKinsey, Goldman Sachs, and Deloitte.
Your infographics win awards. Every pixel is intentional. Clients pay £50,000 for your work.

TASK: Generate a complete, self-contained HTML infographic from the user's description.

══ STRICT COLOR PALETTE ══
#DB0011  → Signature Red         (primary accent, key numbers, highlights, borders)
#000000  → Pure Black            (main backgrounds, strong headers)
#1A1A1A  → Rich Black            (section backgrounds)
#2C2C2C  → Dark Charcoal         (card backgrounds)
#666666  → Mid Grey              (secondary text, dividers)
#AAAAAA  → Light Grey            (tertiary text, subtle elements)
#F5F5F5  → Near White            (light backgrounds, alternating rows)
#FFFFFF  → Pure White            (primary text on dark, clean areas)
USE NO OTHER COLORS. Zero exceptions.

══ TYPOGRAPHY ══
Font family: 'Arial', 'Helvetica Neue', sans-serif — ONLY this.
- Hero number:    700 weight, 72-96px, #DB0011 or #FFFFFF
- Section title:  700 weight, 22-28px, #FFFFFF or #DB0011, letter-spacing: 2px, UPPERCASE
- Subsection:     600 weight, 16-18px, #FFFFFF
- Body text:      400 weight, 12-14px, #AAAAAA or #FFFFFF
- Labels:         700 weight, 10-11px, UPPERCASE, letter-spacing: 1.5px

══ CANVAS DIMENSIONS ══
Width: {width}px  Height: {height}px  (FIXED — do not exceed)
Use: <div style="width:{width}px;height:{height}px;overflow:hidden;"> as root container.

══ INFOGRAPHIC TYPE: {inf_type.upper()} ══
Design the layout specifically for this type:
- STATISTICS: Big bold numbers grid, percentage rings (CSS), comparison bars
- PROCESS: Numbered steps with connecting arrows, phase headers
- TIMELINE: Horizontal or vertical flow with dates/milestones
- COMPARISON: Split left/right or top/bottom columns
- INSIGHTS: Hierarchy with key quotes, bullet stats, call-outs
- HIERARCHY: Pyramid or org structure with levels
- AUTO: Claude chooses best layout for the content

══ MANDATORY DESIGN ELEMENTS ══
1. HEADER BAND: Full-width #DB0011 or #000000 bar — App title + subtitle
2. RED ACCENT LINES: 2-3px horizontal red dividers between sections
3. BIG NUMBERS: At least 2-3 large statistics (60px+) if data exists
4. PROGRESS BARS: CSS-only bars using #DB0011 fill on #2C2C2C background
5. SECTION BOXES: Cards with 1px solid #DB0011 border or #2C2C2C background
6. GEOMETRIC SHAPES: Red squares/circles as bullet points or decorations
7. FOOTER BAND: Dark footer with source/date/branding
8. WATERMARK AREA: Bottom right — "Generated by AI" in 10px #666666

══ CSS TECHNIQUES (use these for wow factor) ══
- CSS Grid for main layout: display:grid; grid-template-columns: ...
- Flexbox for alignment
- CSS custom progress bars: height:8px; border-radius:4px
- CSS circles: border-radius:50%; width/height equal
- CSS triangles for arrows: border tricks
- Border-left: 4px solid #DB0011 for stat callouts
- Box-shadow: 0 4px 20px rgba(219,0,17,0.15) for card glow
- text-transform: uppercase + letter-spacing for headers
- Linear gradients: background: linear-gradient(135deg, #1A1A1A, #2C2C2C)

══ QUALITY STANDARDS ══
✓ Looks like a £50,000 corporate board presentation slide
✓ Viewer stops scrolling and says "WOW"
✓ Perfect visual hierarchy — eye flows naturally
✓ No wasted space — every area serves a purpose
✓ Data is clearly readable at a glance
✓ Professional enough for C-suite presentation
✓ Zero comic elements, zero casual design choices

══ OUTPUT FORMAT ══
Return ONLY the raw HTML document.
- Starts with <!DOCTYPE html>
- All CSS in <style> tag — NO external stylesheets
- NO JavaScript
- NO external fonts (Arial is system font, always available)
- HTML must render perfectly at exactly {width}×{height}px
- Self-contained — works with no internet connection
- Do NOT wrap in markdown code fences
- Do NOT add any explanation before or after the HTML"""

# ── CSS ───────────────────────────────────────────────────────────────────────
def inject_css():
    st.markdown("""
<style>
[data-testid="stAppViewContainer"] { background:#0f0f0f; }
[data-testid="stHeader"]           { background:transparent; }

[data-testid="metric-container"] {
    background:#1a1a1a; border:1px solid #DB0011;
    border-radius:8px; padding:16px 20px;
}
[data-testid="stMetricLabel"] { color:#666 !important; font-size:.8rem !important;
    text-transform:uppercase; letter-spacing:.05em; }
[data-testid="stMetricValue"] { color:#fff !important; font-size:1.6rem !important; font-weight:700 !important; }

.stButton>button {
    background:linear-gradient(135deg,#DB0011,#a30000) !important;
    color:white !important; border:none !important;
    border-radius:4px !important; font-weight:700 !important;
    font-size:1rem !important; letter-spacing:.05em !important;
    text-transform:uppercase !important;
    transition:all .2s !important;
}
.stButton>button:hover { opacity:.85 !important; transform:translateY(-1px) !important; }

[data-testid="stTextArea"] textarea {
    background:#1a1a1a !important; border:1px solid #333 !important;
    color:#f1f5f9 !important; border-radius:4px !important;
    font-size:14px !important;
}
[data-testid="stTextArea"] textarea:focus { border-color:#DB0011 !important; }

[data-testid="stSelectbox"] > div { background:#1a1a1a !important; border-color:#333 !important; }

.stDownloadButton>button {
    background:linear-gradient(135deg,#1a1a1a,#2c2c2c) !important;
    border:1px solid #DB0011 !important; color:#DB0011 !important;
    font-weight:700 !important; letter-spacing:.05em !important;
    text-transform:uppercase !important;
}
.stDownloadButton>button:hover { background:#DB0011 !important; color:white !important; }

[data-testid="stTabs"] [role="tab"] { color:#666 !important; font-weight:600 !important; }
[data-testid="stTabs"] [role="tab"][aria-selected="true"] {
    color:#DB0011 !important; border-bottom:2px solid #DB0011 !important; }

.preview-frame {
    border: 2px solid #DB0011;
    border-radius: 4px;
    overflow: hidden;
    margin: 0 auto;
}
hr { border-color:#2c2c2c !important; }
</style>""", unsafe_allow_html=True)

# ── Generate HTML via Claude ──────────────────────────────────────────────────
def generate_html(description: str, inf_type: str, width: int, height: int,
                  extra_notes: str, client: anthropic.Anthropic) -> str:
    user_msg = f"""Create a professional infographic for the following:

DESCRIPTION:
{description}

INFOGRAPHIC TYPE: {inf_type}
CANVAS SIZE: {width} × {height} px
"""
    if extra_notes.strip():
        user_msg += f"\nADDITIONAL INSTRUCTIONS:\n{extra_notes}"

    user_msg += "\n\nReturn ONLY the raw HTML. No markdown, no explanation."

    with st.spinner("🎨 Claude is designing your infographic…"):
        response = client.messages.create(
            model="claude-opus-4-7",
            max_tokens=8000,
            thinking={"type": "adaptive"},
            system=build_system_prompt(inf_type, width, height),
            messages=[{"role": "user", "content": user_msg}]
        )

    # Extract text block
    html = ""
    for block in response.content:
        if block.type == "text":
            html = block.text
            break

    # Strip any accidental markdown fences
    html = html.strip()
    if html.startswith("```"):
        lines = html.split("\n")
        html = "\n".join(lines[1:-1] if lines[-1].strip() == "```" else lines[1:])
    return html

# ── Render HTML → JPG via Playwright ─────────────────────────────────────────
def render_to_jpg(html: str, width: int, height: int) -> bytes:
    from playwright.sync_api import sync_playwright
    with sync_playwright() as p:
        browser = p.chromium.launch(args=["--no-sandbox", "--disable-dev-shm-usage"])
        page = browser.new_page(viewport={"width": width, "height": height})
        page.set_content(html, wait_until="networkidle")
        page.wait_for_timeout(800)   # let CSS transitions settle
        screenshot = page.screenshot(
            type="jpeg", quality=97,
            clip={"x": 0, "y": 0, "width": width, "height": height}
        )
        browser.close()
    return screenshot

# ── Render HTML → PPTX via python-pptx ───────────────────────────────────────
def render_to_pptx(jpg_bytes: bytes, html: str, width: int, height: int,
                   description: str) -> bytes:
    """
    Builds an editable PowerPoint file:
      Slide 1 — Full-bleed infographic image (design-perfect, click any element to move/resize)
      Slide 2 — Plain-text outline with key content extracted from HTML, fully editable
    """
    try:
        from pptx import Presentation
        from pptx.util import Emu, Pt
        from pptx.dml.color import RGBColor
        from pptx.enum.text import PP_ALIGN
    except ImportError:
        raise RuntimeError("python-pptx not installed. Run: pip install python-pptx")

    try:
        from bs4 import BeautifulSoup
        _has_bs4 = True
    except ImportError:
        _has_bs4 = False

    EMU_PX = 9525          # 1px = 9525 EMU at 96 DPI
    RED    = RGBColor(0xDB, 0x00, 0x11)
    BLACK  = RGBColor(0x00, 0x00, 0x00)
    WHITE  = RGBColor(0xFF, 0xFF, 0xFF)
    GREY   = RGBColor(0xAA, 0xAA, 0xAA)

    prs = Presentation()
    prs.slide_width  = Emu(width  * EMU_PX)
    prs.slide_height = Emu(height * EMU_PX)

    # ── Slide 1: Full-bleed infographic image ──────────────────────────────────
    slide1 = prs.slides.add_slide(prs.slide_layouts[6])   # blank
    img_io = io.BytesIO(jpg_bytes)
    pic = slide1.shapes.add_picture(img_io, 0, 0,
                                    prs.slide_width, prs.slide_height)
    pic.name = "Infographic"

    # ── Slide 2: Editable text outline ────────────────────────────────────────
    slide2 = prs.slides.add_slide(prs.slide_layouts[6])   # blank

    # Black background
    bg = slide2.background
    fill = bg.fill
    fill.solid()
    fill.fore_color.rgb = BLACK

    PAD  = Emu(36 * EMU_PX)   # 36px padding
    W    = prs.slide_width  - PAD * 2
    H    = prs.slide_height - PAD * 2

    def add_txbox(slide, text, left, top, w, h,
                  size=14, bold=False, color=WHITE, align=PP_ALIGN.LEFT):
        txb = slide.shapes.add_textbox(left, top, w, h)
        tf  = txb.text_frame
        tf.word_wrap = True
        p   = tf.paragraphs[0]
        p.alignment = align
        run = p.add_run()
        run.text = text
        run.font.size  = Pt(size)
        run.font.bold  = bold
        run.font.color.rgb = color
        return txb

    # Red top bar
    bar = slide2.shapes.add_shape(
        1,   # MSO_SHAPE_TYPE.RECTANGLE
        0, 0, prs.slide_width, Emu(8 * EMU_PX)
    )
    bar.fill.solid(); bar.fill.fore_color.rgb = RED
    bar.line.fill.background()

    cursor_y = Emu(20 * EMU_PX)

    # Title
    add_txbox(slide2, "INFOGRAPHIC — EDITABLE CONTENT",
              PAD, cursor_y, W, Emu(50 * EMU_PX),
              size=22, bold=True, color=RED)
    cursor_y += Emu(60 * EMU_PX)

    # Description block
    add_txbox(slide2, "ORIGINAL DESCRIPTION",
              PAD, cursor_y, W, Emu(20 * EMU_PX),
              size=9, bold=True, color=GREY)
    cursor_y += Emu(22 * EMU_PX)
    add_txbox(slide2, description,
              PAD, cursor_y, W, Emu(80 * EMU_PX),
              size=12, bold=False, color=WHITE)
    cursor_y += Emu(90 * EMU_PX)

    # Divider line
    ln = slide2.shapes.add_shape(1, PAD, cursor_y, W, Emu(2 * EMU_PX))
    ln.fill.solid(); ln.fill.fore_color.rgb = RED
    ln.line.fill.background()
    cursor_y += Emu(16 * EMU_PX)

    # Extract text from HTML
    if _has_bs4:
        soup = BeautifulSoup(html, "html.parser")
        for tag in soup(["script", "style"]): tag.decompose()
        raw_text = soup.get_text(separator="\n")
        lines = [l.strip() for l in raw_text.splitlines() if l.strip()]
        # Deduplicate while preserving order
        seen = set(); unique_lines = []
        for l in lines:
            if l not in seen and len(l) > 2:
                seen.add(l); unique_lines.append(l)
        content_text = "\n".join(unique_lines[:60])   # cap at 60 lines
    else:
        content_text = "Install beautifulsoup4 to auto-extract text content."

    add_txbox(slide2, "EXTRACTED CONTENT (EDITABLE)",
              PAD, cursor_y, W, Emu(20 * EMU_PX),
              size=9, bold=True, color=GREY)
    cursor_y += Emu(22 * EMU_PX)

    remaining_h = prs.slide_height - cursor_y - PAD
    add_txbox(slide2, content_text,
              PAD, cursor_y, W, remaining_h,
              size=11, bold=False, color=WHITE)

    # ── Save ──────────────────────────────────────────────────────────────────
    out = io.BytesIO()
    prs.save(out)
    return out.getvalue()


# ── Size presets ──────────────────────────────────────────────────────────────
SIZE_PRESETS = {
    "📊 Presentation (1200×900)":    (1200, 900),
    "📱 Portrait / Social (900×1200)": (900, 1200),
    "⬛ Square / Instagram (1080×1080)": (1080, 1080),
    "🖥️ Widescreen Banner (1920×600)": (1920, 600),
    "📄 A4 Landscape (1122×794)":    (1122, 794),
}

INF_TYPES = [
    "Auto (Claude decides)",
    "Statistics & Numbers",
    "Process Flow",
    "Timeline",
    "Comparison",
    "Key Insights",
    "Hierarchy / Structure",
    "Dashboard Overview",
]

# ═════════════════════════════════════════════════════════════════════════════
def main():
    st.set_page_config(
        page_title="AI Infographic Generator",
        page_icon="🎨",
        layout="wide",
        initial_sidebar_state="collapsed",
    )
    inject_css()
    install_playwright()

    # Session state
    if "history" not in st.session_state: st.session_state.history = []
    if "current_html" not in st.session_state: st.session_state.current_html = None
    if "current_jpg" not in st.session_state: st.session_state.current_jpg = None
    if "current_name" not in st.session_state: st.session_state.current_name = None

    # Load .env for secrets
    try:
        from dotenv import load_dotenv
        load_dotenv(dotenv_path=os.path.join(os.path.dirname(__file__), ".env"))
    except Exception:
        pass
    try:
        if "ANTHROPIC_API_KEY" in st.secrets:
            os.environ["ANTHROPIC_API_KEY"] = st.secrets["ANTHROPIC_API_KEY"]
    except Exception:
        pass

    # ── Sidebar ───────────────────────────────────────────────────────────────
    with st.sidebar:
        st.markdown("### ⚙️  Settings")
        api_key = st.text_input("Anthropic API Key",
                                 value=os.getenv("ANTHROPIC_API_KEY",""),
                                 type="password")
        if api_key: os.environ["ANTHROPIC_API_KEY"] = api_key

        st.markdown("---")
        st.markdown("**Design System**")
        st.markdown("""
<div style='font-size:.85rem;color:#666;'>
🔴 <b style='color:#DB0011;'>#DB0011</b> Signature Red<br>
⬛ <b style='color:#fff;'>#000000</b> Black<br>
⬜ <b style='color:#f5f5f5;'>#F5F5F5</b> White<br><br>
Font: Arial / Helvetica Neue<br>
Powered by Claude Opus 4.7
</div>""", unsafe_allow_html=True)

    # ── Header ────────────────────────────────────────────────────────────────
    st.markdown("""
<div style='background:#000;border-bottom:3px solid #DB0011;padding:20px 0 16px 0;margin-bottom:20px;'>
  <h1 style='margin:0;color:#fff;font-size:2rem;font-family:Arial,sans-serif;font-weight:900;
             letter-spacing:-0.5px;'>
    <span style='color:#DB0011;'>■</span>&nbsp; AI INFOGRAPHIC GENERATOR
  </h1>
  <p style='margin:4px 0 0 0;color:#666;font-size:.9rem;font-family:Arial,sans-serif;
            letter-spacing:1px;text-transform:uppercase;'>
    Professional Templates  ·  White · Black · Red  ·  Powered by Claude Opus 4.7
  </p>
</div>""", unsafe_allow_html=True)

    if not os.getenv("ANTHROPIC_API_KEY"):
        st.warning("⚠️  Enter your Anthropic API key in the sidebar to start.")
        st.stop()

    # ── Main Tabs ─────────────────────────────────────────────────────────────
    tab1, tab2 = st.tabs(["🎨  Create Infographic", "📚  History"])

    # ════════════════════════════════════════════════════════════════════════
    with tab1:
        col_left, col_right = st.columns([1, 1.3], gap="large")

        with col_left:
            st.markdown("##### 📝  Describe Your Infographic")
            description = st.text_area(
                "Enter your content, data, or topic",
                height=220,
                placeholder="""Examples:
• Q3 2025 Financial Results: Revenue £14.2B (+8%), Net Profit £3.1B (+12%), Cost-to-Income 48%, Tier 1 Capital 15.2%. Markets: Asia Pacific leads with 42% contribution.

• 5-step digital transformation roadmap: 1. Assess 2. Plan 3. Pilot 4. Scale 5. Optimise

• Compare traditional banking vs digital banking across: Speed, Cost, Accessibility, Security, Customer Experience, Innovation

• Key risks in AML compliance: Transaction monitoring, Name screening, Sanctions, Customer due diligence, Regulatory reporting""",
                label_visibility="collapsed"
            )

            col_type, col_size = st.columns(2)
            with col_type:
                inf_type = st.selectbox("Infographic Type", INF_TYPES,
                                         label_visibility="visible")
            with col_size:
                size_label = st.selectbox("Canvas Size", list(SIZE_PRESETS.keys()),
                                           label_visibility="visible")
            width, height = SIZE_PRESETS[size_label]

            extra = st.text_input(
                "Additional instructions (optional)",
                placeholder="e.g. Focus on risk metrics, add company logo placeholder, make header very bold…"
            )

            gen_col, _ = st.columns([1, 1])
            with gen_col:
                generate = st.button("🎨  GENERATE INFOGRAPHIC", use_container_width=True)

        # ── Generation ────────────────────────────────────────────────────────
        if generate:
            if not description.strip():
                st.error("Please enter a description first.")
            else:
                client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])

                try:
                    # Step 1: Generate HTML
                    html = generate_html(description, inf_type, width, height, extra, client)
                    st.session_state.current_html = html

                    # Step 2: Render to JPG
                    with st.spinner("📸  Rendering high-resolution JPG…"):
                        jpg_bytes = render_to_jpg(html, width, height)
                    st.session_state.current_jpg  = jpg_bytes

                    # Step 3: Save to history
                    ts = datetime.now().strftime("%H:%M:%S")
                    name = f"Infographic_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
                    st.session_state.current_name = name
                    st.session_state.history.insert(0, {
                        "name": name,
                        "ts": ts,
                        "jpg": jpg_bytes,
                        "html": html,
                        "desc": description[:80] + "…" if len(description) > 80 else description,
                        "type": inf_type,
                        "size": f"{width}×{height}",
                    })
                    st.success("✅  Infographic generated successfully!")
                    st.rerun()

                except Exception as e:
                    st.error(f"❌  Error: {str(e)}")

        # ── Preview & Download ────────────────────────────────────────────────
        with col_right:
            if st.session_state.current_jpg:
                st.markdown("##### 👁️  Preview")

                # Display image
                img = Image.open(io.BytesIO(st.session_state.current_jpg))
                st.image(img, use_container_width=True,
                         caption=f"{st.session_state.current_name}  •  {img.size[0]}×{img.size[1]}px")

                st.markdown("<br>", unsafe_allow_html=True)

                # Download + Share row
                d1, d2, d3, d4 = st.columns(4)
                with d1:
                    st.download_button(
                        "⬇️  JPG",
                        data=st.session_state.current_jpg,
                        file_name=f"{st.session_state.current_name}.jpg",
                        mime="image/jpeg",
                        use_container_width=True,
                    )
                with d2:
                    # PNG download (higher quality)
                    png_buf = io.BytesIO()
                    img.save(png_buf, format="PNG")
                    st.download_button(
                        "⬇️  PNG",
                        data=png_buf.getvalue(),
                        file_name=f"{st.session_state.current_name}.png",
                        mime="image/png",
                        use_container_width=True,
                    )
                with d3:
                    # PowerPoint download
                    try:
                        pptx_bytes = render_to_pptx(
                            st.session_state.current_jpg,
                            st.session_state.current_html,
                            width, height,
                            description,
                        )
                        st.download_button(
                            "⬇️  PPTX",
                            data=pptx_bytes,
                            file_name=f"{st.session_state.current_name}.pptx",
                            mime="application/vnd.openxmlformats-officedocument.presentationml.presentation",
                            use_container_width=True,
                            help="Slide 1: full infographic image  |  Slide 2: editable text outline",
                        )
                    except Exception as pptx_err:
                        st.error(f"PPTX error: {pptx_err}")
                with d4:
                    # Download HTML source
                    st.download_button(
                        "⬇️  HTML",
                        data=st.session_state.current_html.encode("utf-8"),
                        file_name=f"{st.session_state.current_name}.html",
                        mime="text/html",
                        use_container_width=True,
                    )

                # HTML source toggle
                with st.expander("🔍  View HTML Source"):
                    st.code(st.session_state.current_html[:3000] + "…"
                            if len(st.session_state.current_html) > 3000
                            else st.session_state.current_html,
                            language="html")

            else:
                st.markdown("""
<div style='background:#1a1a1a;border:2px dashed #333;border-radius:4px;
            padding:80px 40px;text-align:center;margin-top:10px;'>
  <div style='font-size:3rem;margin-bottom:16px;'>🎨</div>
  <h3 style='color:#fff;font-family:Arial,sans-serif;letter-spacing:1px;
             text-transform:uppercase;margin:0 0 8px 0;'>Your Infographic Appears Here</h3>
  <p style='color:#666;font-family:Arial,sans-serif;font-size:.9rem;'>
    Describe your content on the left and click Generate</p>
  <br>
  <div style='display:flex;justify-content:center;gap:12px;flex-wrap:wrap;'>
    <span style='background:#2c2c2c;color:#DB0011;padding:6px 14px;
                 border:1px solid #DB0011;font-size:.8rem;font-weight:700;
                 letter-spacing:1px;text-transform:uppercase;'>PROFESSIONAL</span>
    <span style='background:#2c2c2c;color:#DB0011;padding:6px 14px;
                 border:1px solid #DB0011;font-size:.8rem;font-weight:700;
                 letter-spacing:1px;text-transform:uppercase;'>CORPORATE STYLE</span>
    <span style='background:#2c2c2c;color:#DB0011;padding:6px 14px;
                 border:1px solid #DB0011;font-size:.8rem;font-weight:700;
                 letter-spacing:1px;text-transform:uppercase;'>DOWNLOAD READY</span>
  </div>
</div>""", unsafe_allow_html=True)

    # ════════════════════════════════════════════════════════════════════════
    with tab2:
        st.markdown("#### 📚  Generated Infographics")
        if not st.session_state.history:
            st.info("No infographics generated yet. Create your first one!")
        else:
            st.caption(f"{len(st.session_state.history)} infographic(s) generated this session")
            cols = st.columns(3)
            for i, item in enumerate(st.session_state.history):
                with cols[i % 3]:
                    st.markdown(f"""
<div style='background:#1a1a1a;border:1px solid #2c2c2c;border-top:2px solid #DB0011;
            border-radius:4px;padding:12px;margin-bottom:12px;'>
  <div style='color:#fff;font-weight:700;font-size:.85rem;
              text-transform:uppercase;letter-spacing:.5px;margin-bottom:4px;'>
    {item["type"][:20]}</div>
  <div style='color:#666;font-size:.8rem;margin-bottom:6px;'>{item["ts"]} · {item["size"]}</div>
  <div style='color:#aaa;font-size:.82rem;'>{item["desc"]}</div>
</div>""", unsafe_allow_html=True)
                    img_h = Image.open(io.BytesIO(item["jpg"]))
                    st.image(img_h, use_container_width=True)
                    hc1, hc2 = st.columns(2)
                    with hc1:
                        st.download_button(
                            "⬇️ JPG",
                            data=item["jpg"],
                            file_name=f"{item['name']}.jpg",
                            mime="image/jpeg",
                            key=f"dl_jpg_{i}",
                            use_container_width=True,
                        )
                    with hc2:
                        try:
                            w_i, h_i = [int(x) for x in item["size"].split("×")]
                            pptx_h = render_to_pptx(
                                item["jpg"], item["html"],
                                w_i, h_i, item["desc"]
                            )
                            st.download_button(
                                "⬇️ PPTX",
                                data=pptx_h,
                                file_name=f"{item['name']}.pptx",
                                mime="application/vnd.openxmlformats-officedocument.presentationml.presentation",
                                key=f"dl_pptx_{i}",
                                use_container_width=True,
                            )
                        except Exception:
                            pass

    # ── Footer ────────────────────────────────────────────────────────────────
    st.markdown("""
<div style='border-top:1px solid #2c2c2c;margin-top:40px;padding:16px 0;
            text-align:center;font-family:Arial,sans-serif;'>
  <span style='color:#333;font-size:.75rem;letter-spacing:1px;text-transform:uppercase;'>
    ■ AI INFOGRAPHIC GENERATOR &nbsp;·&nbsp; PROFESSIONAL CORPORATE STYLE &nbsp;·&nbsp;
    POWERED BY CLAUDE OPUS 4.7
  </span>
</div>""", unsafe_allow_html=True)


if __name__ == "__main__":
    main()
